[package]
name = "neoncore"
version = "0.1.0"
authors = ["Matheus Xavier <mxavier@neonlayer.com>"]
license = "BSD-3-Clause"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
